#ifndef DEBUGCATEGORIES_H
#define DEBUGCATEGORIES_H

#include <QDebug>
#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(dcMap)
Q_DECLARE_LOGGING_CATEGORY(dcGame)
Q_DECLARE_LOGGING_CATEGORY(dcItem)
Q_DECLARE_LOGGING_CATEGORY(dcWorld)
Q_DECLARE_LOGGING_CATEGORY(dcPlayer)
Q_DECLARE_LOGGING_CATEGORY(dcCollision)
Q_DECLARE_LOGGING_CATEGORY(dcConversation)
Q_DECLARE_LOGGING_CATEGORY(dcPlayerController)

#endif // DEBUGCATEGORIES_H
